Breaddit/config/routes.rb
Rails.application.routes.draw do
  resources :subs 
  resources :posts

  resources :users

  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Breaddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :text             not null
#  mod_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
    validates :title, :description, :mod_id, presence: true

    belongs_to :mod, 
        foreign_key: :mod_id,
        class_name: :User

    has_many :posts
end

Breaddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(sub_params)
    @sub.mod_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub }
      else
        format.html { render :edit }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub.destroy
    respond_to do |format|
      format.html { redirect_to subs_url, notice: 'Sub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

Breaddit/app/helpers/subs_helper.rb
module SubsHelper
end

Breaddit/app/views/subs/_form.html.erb
<%= form_with(model: sub, local: true) do |form| %>
  <% if sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
      <% sub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

Breaddit/app/views/subs/edit.html.erb
<h1>Editing Sub</h1>

<%= render 'form', sub: @sub %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

Breaddit/app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= link_to sub.title, sub %></td>
        <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
        <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

Breaddit/app/views/subs/new.html.erb
<h1>New Sub</h1>

    <form action="<%= subs_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <label>Sub Title
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
        </label>

        <label>Description
        <input type="text" name="sub[description]" value="<%= @sub.description %>">
        </label>

        <input type="submit" value="Create Sub">
    </form>

<%= link_to 'Back', subs_path %>

Breaddit/app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @sub.title %></h1>
<br>
<%= @sub.description %>

<br>
Posts
<ul>
<% @sub.posts.each do |post| %>
    <%= link_to post.title , posts_url %>
<% end %>
</ul>

<br>
<%= link_to "New Post", new_post_url %>



<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>